# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

api_key: 'key-0d41b4af6603150710302be6ed87797a'
domain: 'sandboxbc90aa2b8b474b5e9bb53d96ed2359a8.mailgun.org'
username: 'postmaster@sandboxbc90aa2b8b474b5e9bb53d96ed2359a8.mailgun.org'
password: '78d556519a7b6f6c7e0374eecd701e60'
gmail_username: 'chalado1@gmail.com'
gmail_password: 'Gr01n314;'